# Site settings
name: Thahsin Begum
email: thahsin.begum.78676@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Subject Matter Expert, Problem Solver, Mathematical Trainer, Mathematical Instructor, Domain Expert, Complex and Advanced Problem Solving, Thahsin Begum, Chennai, Startups, Agile, Tech, Trainer"
skills: "Subject Matter Expert ( Advanced Mathematics ) in Chennai, IN"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
# social:
#   - title: linkedin
#     url: https://www.linkedin.com/in/arivazhagan-l-275aaab1/
#   - title: medium
#     url: https://medium.com/@arivbits
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 2196F3
  primary-rgb: "33, 150, 243"
  secondary: 285172
  secondary-dark: 29455b
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
